pipeline {
    agent any

    tools {
        jdk    'Java-21'
        maven 'Maven'
    }

    environment {
        APP_NAME   = 'mi-app-java'
        MAVEN_OPTS = '-Xmx1024m -XX:MaxMetaspaceSize=512m'
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'java -version'
                sh 'mvn -version'
            }
        }

        stage('Compilar y Test') {
            steps {
                // Cambiado a 'examen-tests' que es la carpeta que se ve en tu GitHub
                dir('examen-tests') {
                    sh 'mvn clean compile'
                    sh 'mvn test'
                }
            }
            post {
                always {
                    dir('examen-tests') {
                        junit '**/target/surefire-reports/*.xml'
                    }
                }
            }
        }

        stage('Empaquetar') {
            steps {
                dir('examen-tests') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo '✅ Build completado con éxito'
        }
        failure {
            echo '❌ Build fallido'
        }
        always {
            cleanWs()
        }
    }
}
